-- AlterEnum
ALTER TYPE "ActivityVerb" ADD VALUE 'AGENT_REASONING_STARTED';
ALTER TYPE "ActivityVerb" ADD VALUE 'AGENT_REASONING_COMPLETED';
ALTER TYPE "ActivityVerb" ADD VALUE 'AGENT_REASONING_FAILED';
